name: IndustrialStacking
version: '${project.version}'
main: com.conorsmine.net.industrialstacking.IndustrialStacking
author: Conorsmine
depend: [NBTAPI]
api-version: 1.12

commands:
  industrialStacking:
    description: Main command for the plugin.
    aliases: [is, istk]

permissions:
  IndustrialStacking.*:
    description: Adming permission for all commands.

  # View
  IndsutrialStacking.viewMachines:
    description: Adds a border around or stacked machines in the users vicinity.

  # List
  IndsutrialStacking.listMachines:
    description: Lists all stacked machines.

  # Find
  IndustrialStacking.find.*:
    description: Admin permission for all find commands.

  # Reloading
  IndustrialStacking.reload.*:
    description: Admin permission for all reload commands.
    children: [IndustrialStacking.reload.all]

  IndustrialStacking.reload.all:
    description: Permission for all reload commands.

  IndustrialStacking.reload.plugin:
    description: Permission to apply changes from the config file.

  IndustrialStacking.reload.mod:
    description: Permission to apply changes from the mods config files.

  IndustrialStacking.reload.save:
    description: Permission to apply chanes from the saves file.
