name: IndustrialStacking
version: '${project.version}'
main: com.conorsmine.net.industrialstacking.IndustrialStacking
author: Conorsmine
depend: [NBTAPI]
api-version: 1.13

commands:
  reloadStackables:
    description: Reload the plugin, mainly the config file.
    permission: IndustrialStacking.reload
